spring:
  application:
    name: bd_service
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    hikari:
      schema: api_db
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: postgres

server:
  port: ${PORT:8088}
  servlet:
    context-path: /